export const AUTH={
    "SET_USER":"SET_USER",
    "SET_USER_ACCESS":"SET_USER_ACCESS"
}

export const GLOBAL={
    "SET_NAME":"SET_NAME",
    "SET_FIELDS":"SET_FIELDS",
    "SET_COLUMNS":"SET_COLUMNS",
    "SET_DATA":"SET_DATA",
    "SET_PATH":"SET_PATH",
    "SET_COUNT":"SET_COUNT",
    "SET_ID_FIELD":"SET_ID_FIELD",
    "SET_LOADING":"SET_LOADING",
    "ADD_DATA":"ADD_DATA",
    "SET_ORDER_FIELD":"SET_ORDER_FIELD",
    "SET_FK_FIELDS":"SET_FK_FIELDS",
    "SET_FK_OBJ_FIELDS":"SET_FK_OBJ_FIELDS",
    "SET_TABLE_VIEW_FIELDS":"SET_TABLE_VIEW_FIELDS",
    "SET_LOADED_OBJ":"SET_LOADED_OBJ",
    "SET_RULES":"SET_RULES",
    "SET_CONTROLLING_FIELDS":"SET_CONTROLLING_FIELDS"
}

export const REFERENCE={
    "SET_REF":"SET_REF",
    "SET_LOADING":"SET_LOADING"
}

export const ROOT={
    "SET_DATA":"SET_DATA"
}